version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: salux-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: salux-user
      POSTGRES_PASSWORD: h34lth-m4n4g3r-2019
      POSTGRES_DB: salux_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: